version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=movie_db
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=24h
      - LOG_LEVEL=debug
    depends_on:
      - postgres
    networks:
      - movie-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movie_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movie-network

volumes:
  postgres_data:

networks:
  movie-network:
    driver: bridge
